name: aljabr_sdk
description: "Aljabr Plugin SDK - Public interface and decoupled contracts for plugin development."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  aljabr_plugin_api:
    path: ../aljabr_plugin_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
