name: aljabr_extension
description: "Aljabr modular extension layer bridging plugin API and runtime."
version: 0.0.1
homepage:

environment:
  sdk: ^3.13.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  aljabr_plugin_api:
    path: ../aljabr_plugin_api
  aljabr_plugin_runtime:
    path: ../aljabr_plugin_runtime

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
