// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/chat/models/attachment_dto.dart';
import 'features/chat/models/chat_entry_dto.dart';
import 'features/chat/models/session_dto.dart';
import 'features/dashboard/models/metrics_entry.dart';
import 'features/settings/models/app_settings_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5573946081352630543),
    name: 'AttachmentEntity',
    lastPropertyId: const obx_int.IdUid(15, 1918111963115919794),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2142391013719653998),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2058606423127348384),
        name: 'attachmentId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5584044600224390142),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7199938502797832932),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 670838587410049862),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1940638709340646255),
        name: 'localPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 955830314968431433),
        name: 'size',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2976194752203842835),
        name: 'mimeType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3474244345045635411),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 693587594419937203),
        name: 'thumbnailUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2935214185276506216),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7653448421540285829),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5484316734818084777),
        name: 'chatEntryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 8788077138858081440),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1918111963115919794),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1493093981623455397),
    name: 'ChatEntryEntity',
    lastPropertyId: const obx_int.IdUid(34, 70484784501424545),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4286389123483281567),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2832651591678639824),
        name: 'entryId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 1135966263290422378),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7616233879166974219),
        name: 'sessionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 4287026536032861800),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 248843019098988281),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3913838583229996393),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1472029592206042450),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 478490449322308906),
        name: 'isLoading',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2375448565581045755),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7849280564054928110),
        name: 'toolCallId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8922010580953003237),
        name: 'toolCallKindIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7780293375228248911),
        name: 'toolCallSummary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4742911524765677529),
        name: 'toolCallDetailInput',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4907098599780249032),
        name: 'toolCallDetailOutput',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4551902840404611298),
        name: 'toolCallStatusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7489851968311076088),
        name: 'toolCallRiskIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4501517056133483305),
        name: 'toolCallDurationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3820424860841094499),
        name: 'toolCallErrorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 5682457607113828188),
        name: 'toolCallSubtasks',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6853110052476904205),
        name: 'toolCallResult',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 2608413494134208848),
        name: 'toolCallProgress',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 479272169526585704),
        name: 'toolCallIsBlocking',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3661690310945753650),
        name: 'approvalId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 3206893966287594523),
        name: 'approvalCommand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 5173002554658731773),
        name: 'approvalReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 4306250595899902222),
        name: 'approvalRiskIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 7196989502615780429),
        name: 'approvalStatusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 4520851077646469505),
        name: 'planTitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7100582352519355086),
        name: 'planSteps',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 4523917552770330717),
        name: 'errorMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 3041908783912700582),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 5719065742443392762),
        name: 'jobId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 4818371522724465600),
        name: 'queuePosition',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 70484784501424545),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2605325599257901454),
    name: 'MetricsEntry',
    lastPropertyId: const obx_int.IdUid(24, 7592808395141473348),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6616396295516769311),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2738531864964570429),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3449951963121992678),
        name: 'sessionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4446991241544926416),
        name: 'modelName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 22268224129323844),
        name: 'backend',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1431011589589293135),
        name: 'device',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8693045492800897844),
        name: 'generationSpeedTps',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1448609668338073450),
        name: 'totalTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2788745597661616344),
        name: 'tokenLatencyMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3504088205337080363),
        name: 'openTimeMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1884189913859954022),
        name: 'generateCallMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 325270653594155158),
        name: 'nativeLoadMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 25263498345454072),
        name: 'nativePromptMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 329368261307262814),
        name: 'nativeDecodeMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5330215862289332672),
        name: 'nativeTokenizeMs',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 9155012270787743977),
        name: 'cacheMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8877316707592846220),
        name: 'sessionType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3064104607310034284),
        name: 'promptTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 1952835495083200420),
        name: 'sampledTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3522121381916519866),
        name: 'decodedTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6197119910560467597),
        name: 'gpuLayers',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 3796579410574050948),
        name: 'threads',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 8817663876929472190),
        name: 'contextSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7592808395141473348),
        name: 'outputBytes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7560878492137478190),
    name: 'SessionEntity',
    lastPropertyId: const obx_int.IdUid(20, 6520579992285216565),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3849484806908630678),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4845133993591775464),
        name: 'sessionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 2545134704468929306),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8303308733287250207),
        name: 'projectId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 6642064833448594494),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3139262740095179930),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1630650629069679431),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3861662717598404079),
        name: 'statusIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 295765188277322906),
        name: 'modeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2050074893507280110),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3971923138629871013),
        name: 'updatedAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 718589136061964499),
        name: 'lastActiveAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 637998894282075792),
        name: 'forkOf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 41302777680669759),
        name: 'isPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1592352521021667767),
        name: 'fileChanges',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1669393894583617362),
        name: 'messageCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4245898909312370068),
        name: 'pendingCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 80018069498990566),
        name: 'queueSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2079909009110137992),
        name: 'totalDurationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 984920186111113177),
        name: 'isSelected',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 6520579992285216565),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8868744722431710510),
    name: 'AppSettingsEntity',
    lastPropertyId: const obx_int.IdUid(57, 8494574281485153073),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 299728365164209185),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6353095835600336546),
        name: 'themeMode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1641334788834800919),
        name: 'conversationWidth',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8214836146383611541),
        name: 'lightThemePreset',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 518773090202131732),
        name: 'darkThemePreset',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3241794467458126438),
        name: 'verboseAgentChat',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8162379269882426957),
        name: 'fontSize',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 871646315694225599),
        name: 'aiProvider',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2770507019837852632),
        name: 'apiKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4352624397636653505),
        name: 'wayangProBaseUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 563522607242927064),
        name: 'wayangProGrpcUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7473354874397866967),
        name: 'openAiBaseUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 780914765253908371),
        name: 'anthropicBaseUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3328084206896992854),
        name: 'geminiBaseUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7288131012564577574),
        name: 'defaultModel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4141880167725786459),
        name: 'systemPrompt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3285439588090609560),
        name: 'streamingEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 986852214421245941),
        name: 'maxTokens',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 5053408832033070701),
        name: 'temperature',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3733998665973305501),
        name: 'autoSelectModel',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6598486261142635550),
        name: 'localLlmBackend',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5312025577778294432),
        name: 'localModelPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 3375632477091512314),
        name: 'localModelName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 5397894569959071302),
        name: 'localContextSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 1014682205785513034),
        name: 'localGpuLayers',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 7114164956853085487),
        name: 'localThreads',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 1628401126213519997),
        name: 'ollamaBaseUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 210247612992990626),
        name: 'localEnableGpu',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 2426216639510758435),
        name: 'securityPreset',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 4706281611766633164),
        name: 'outsideFolderFileAccess',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 7298122384808385598),
        name: 'terminalExecutionPolicy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 2935218802409421118),
        name: 'sandboxMode',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 4826376580177796155),
        name: 'artifactReviewPolicy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 8435738630411132940),
        name: 'fileAccessRulesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 6887083750419932490),
        name: 'networkAccessRulesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 229656733974733444),
        name: 'terminalCommandsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(37, 6406583238505112658),
        name: 'mcpToolsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(38, 1235268981053033165),
        name: 'jsExecutionPolicy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(39, 381633466382072883),
        name: 'browserViewportWidth',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(40, 2858739689948788326),
        name: 'browserViewportHeight',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(41, 4635848044497301128),
        name: 'downloadPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 6844823629058798437),
        name: 'screenshotEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 1135112457909628389),
        name: 'actuationRulesJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 747819556716361109),
        name: 'desktopNotifications',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(45, 5709477528600172118),
        name: 'soundEffects',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(46, 5771841977776657648),
        name: 'taskCompletionAlert',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(47, 2983025948075141588),
        name: 'errorAlert',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(48, 7636065934444348633),
        name: 'telemetryEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(49, 5647799243812371698),
        name: 'crashReporting',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(50, 7673470810470495341),
        name: 'analyticsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(51, 4405195077352248803),
        name: 'logLevel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(52, 7131259725117798809),
        name: 'autoSave',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(53, 5488953187597573261),
        name: 'autoSaveIntervalSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(54, 1437590500309166855),
        name: 'experimentalFeatures',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(55, 7161763820338441839),
        name: 'proxyUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(56, 5380475311591830342),
        name: 'noProxyHosts',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(57, 8494574281485153073),
        name: 'sslVerification',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 8868744722431710510),
    lastIndexId: const obx_int.IdUid(5, 6642064833448594494),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5398353600855530041,
      2049668289599877013,
      9202612113156994144,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AttachmentEntity: obx_int.EntityDefinition<AttachmentEntity>(
      model: _entities[0],
      toOneRelations: (AttachmentEntity object) => [],
      toManyRelations: (AttachmentEntity object) => {},
      getId: (AttachmentEntity object) => object.id,
      setId: (AttachmentEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AttachmentEntity object, fb.Builder fbb) {
        final attachmentIdOffset = fbb.writeString(object.attachmentId);
        final nameOffset = fbb.writeString(object.name);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final localPathOffset = object.localPath == null
            ? null
            : fbb.writeString(object.localPath!);
        final mimeTypeOffset = object.mimeType == null
            ? null
            : fbb.writeString(object.mimeType!);
        final thumbnailUrlOffset = object.thumbnailUrl == null
            ? null
            : fbb.writeString(object.thumbnailUrl!);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        final chatEntryIdOffset = fbb.writeString(object.chatEntryId);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, attachmentIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.typeIndex);
        fbb.addOffset(4, urlOffset);
        fbb.addOffset(5, localPathOffset);
        fbb.addInt64(6, object.size);
        fbb.addOffset(7, mimeTypeOffset);
        fbb.addInt64(8, object.statusIndex);
        fbb.addOffset(9, thumbnailUrlOffset);
        fbb.addInt64(10, object.durationMs);
        fbb.addOffset(12, errorMessageOffset);
        fbb.addOffset(13, chatEntryIdOffset);
        fbb.addOffset(14, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final attachmentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final localPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final sizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final mimeTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final thumbnailUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final durationMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final chatEntryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final object = AttachmentEntity(
          id: idParam,
          attachmentId: attachmentIdParam,
          name: nameParam,
          typeIndex: typeIndexParam,
          url: urlParam,
          localPath: localPathParam,
          size: sizeParam,
          mimeType: mimeTypeParam,
          statusIndex: statusIndexParam,
          thumbnailUrl: thumbnailUrlParam,
          durationMs: durationMsParam,
          metadataJson: metadataJsonParam,
          errorMessage: errorMessageParam,
          chatEntryId: chatEntryIdParam,
        );

        return object;
      },
    ),
    ChatEntryEntity: obx_int.EntityDefinition<ChatEntryEntity>(
      model: _entities[1],
      toOneRelations: (ChatEntryEntity object) => [],
      toManyRelations: (ChatEntryEntity object) => {},
      getId: (ChatEntryEntity object) => object.id,
      setId: (ChatEntryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatEntryEntity object, fb.Builder fbb) {
        final entryIdOffset = fbb.writeString(object.entryId);
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final textOffset = fbb.writeString(object.text);
        final toolCallIdOffset = object.toolCallId == null
            ? null
            : fbb.writeString(object.toolCallId!);
        final toolCallSummaryOffset = object.toolCallSummary == null
            ? null
            : fbb.writeString(object.toolCallSummary!);
        final toolCallDetailInputOffset = object.toolCallDetailInput == null
            ? null
            : fbb.writeString(object.toolCallDetailInput!);
        final toolCallDetailOutputOffset = object.toolCallDetailOutput == null
            ? null
            : fbb.writeString(object.toolCallDetailOutput!);
        final toolCallErrorMessageOffset = object.toolCallErrorMessage == null
            ? null
            : fbb.writeString(object.toolCallErrorMessage!);
        final toolCallSubtasksOffset = object.toolCallSubtasks == null
            ? null
            : fbb.writeString(object.toolCallSubtasks!);
        final toolCallResultOffset = object.toolCallResult == null
            ? null
            : fbb.writeString(object.toolCallResult!);
        final approvalIdOffset = object.approvalId == null
            ? null
            : fbb.writeString(object.approvalId!);
        final approvalCommandOffset = object.approvalCommand == null
            ? null
            : fbb.writeString(object.approvalCommand!);
        final approvalReasonOffset = object.approvalReason == null
            ? null
            : fbb.writeString(object.approvalReason!);
        final planTitleOffset = object.planTitle == null
            ? null
            : fbb.writeString(object.planTitle!);
        final planStepsOffset = object.planSteps == null
            ? null
            : fbb.writeString(object.planSteps!);
        final errorMessageOffset = object.errorMessage == null
            ? null
            : fbb.writeString(object.errorMessage!);
        final jobIdOffset = object.jobId == null
            ? null
            : fbb.writeString(object.jobId!);
        final metadataJsonOffset = object.metadataJson == null
            ? null
            : fbb.writeString(object.metadataJson!);
        fbb.startTable(35);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, entryIdOffset);
        fbb.addOffset(2, sessionIdOffset);
        fbb.addInt64(3, object.typeIndex);
        fbb.addInt64(4, object.statusIndex);
        fbb.addOffset(5, textOffset);
        fbb.addBool(6, object.isLoading);
        fbb.addInt64(7, object.timestamp);
        fbb.addOffset(8, toolCallIdOffset);
        fbb.addInt64(9, object.toolCallKindIndex);
        fbb.addOffset(10, toolCallSummaryOffset);
        fbb.addOffset(11, toolCallDetailInputOffset);
        fbb.addOffset(12, toolCallDetailOutputOffset);
        fbb.addInt64(13, object.toolCallStatusIndex);
        fbb.addInt64(14, object.toolCallRiskIndex);
        fbb.addInt64(15, object.toolCallDurationMs);
        fbb.addOffset(16, toolCallErrorMessageOffset);
        fbb.addOffset(17, toolCallSubtasksOffset);
        fbb.addOffset(18, toolCallResultOffset);
        fbb.addInt64(19, object.toolCallProgress);
        fbb.addBool(20, object.toolCallIsBlocking);
        fbb.addOffset(21, approvalIdOffset);
        fbb.addOffset(22, approvalCommandOffset);
        fbb.addOffset(23, approvalReasonOffset);
        fbb.addInt64(24, object.approvalRiskIndex);
        fbb.addInt64(25, object.approvalStatusIndex);
        fbb.addOffset(26, planTitleOffset);
        fbb.addOffset(27, planStepsOffset);
        fbb.addOffset(28, errorMessageOffset);
        fbb.addInt64(29, object.retryCount);
        fbb.addOffset(31, jobIdOffset);
        fbb.addInt64(32, object.queuePosition);
        fbb.addOffset(33, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final entryIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final isLoadingParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final toolCallIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final toolCallKindIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final toolCallSummaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final toolCallDetailInputParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final toolCallDetailOutputParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final toolCallStatusIndexParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 30);
        final toolCallRiskIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final toolCallDurationMsParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 34);
        final toolCallErrorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final toolCallSubtasksParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final toolCallResultParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 40);
        final toolCallProgressParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          42,
        );
        final toolCallIsBlockingParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final approvalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 46);
        final approvalCommandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final approvalReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final approvalRiskIndexParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          52,
        );
        final approvalStatusIndexParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 54);
        final planTitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final planStepsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final errorMessageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final retryCountParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          62,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 70);
        final jobIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 66);
        final queuePositionParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          68,
        );
        final object = ChatEntryEntity(
          id: idParam,
          entryId: entryIdParam,
          sessionId: sessionIdParam,
          typeIndex: typeIndexParam,
          statusIndex: statusIndexParam,
          text: textParam,
          isLoading: isLoadingParam,
          timestamp: timestampParam,
          toolCallId: toolCallIdParam,
          toolCallKindIndex: toolCallKindIndexParam,
          toolCallSummary: toolCallSummaryParam,
          toolCallDetailInput: toolCallDetailInputParam,
          toolCallDetailOutput: toolCallDetailOutputParam,
          toolCallStatusIndex: toolCallStatusIndexParam,
          toolCallRiskIndex: toolCallRiskIndexParam,
          toolCallDurationMs: toolCallDurationMsParam,
          toolCallErrorMessage: toolCallErrorMessageParam,
          toolCallSubtasks: toolCallSubtasksParam,
          toolCallResult: toolCallResultParam,
          toolCallProgress: toolCallProgressParam,
          toolCallIsBlocking: toolCallIsBlockingParam,
          approvalId: approvalIdParam,
          approvalCommand: approvalCommandParam,
          approvalReason: approvalReasonParam,
          approvalRiskIndex: approvalRiskIndexParam,
          approvalStatusIndex: approvalStatusIndexParam,
          planTitle: planTitleParam,
          planSteps: planStepsParam,
          errorMessage: errorMessageParam,
          retryCount: retryCountParam,
          metadataJson: metadataJsonParam,
          jobId: jobIdParam,
          queuePosition: queuePositionParam,
        );

        return object;
      },
    ),
    MetricsEntry: obx_int.EntityDefinition<MetricsEntry>(
      model: _entities[2],
      toOneRelations: (MetricsEntry object) => [],
      toManyRelations: (MetricsEntry object) => {},
      getId: (MetricsEntry object) => object.id,
      setId: (MetricsEntry object, int id) {
        object.id = id;
      },
      objectToFB: (MetricsEntry object, fb.Builder fbb) {
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final modelNameOffset = fbb.writeString(object.modelName);
        final backendOffset = fbb.writeString(object.backend);
        final deviceOffset = fbb.writeString(object.device);
        final cacheModeOffset = fbb.writeString(object.cacheMode);
        final sessionTypeOffset = fbb.writeString(object.sessionType);
        fbb.startTable(25);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(2, sessionIdOffset);
        fbb.addOffset(3, modelNameOffset);
        fbb.addOffset(4, backendOffset);
        fbb.addOffset(5, deviceOffset);
        fbb.addFloat64(6, object.generationSpeedTps);
        fbb.addInt64(7, object.totalTokens);
        fbb.addFloat64(8, object.tokenLatencyMs);
        fbb.addFloat64(9, object.openTimeMs);
        fbb.addFloat64(10, object.generateCallMs);
        fbb.addFloat64(11, object.nativeLoadMs);
        fbb.addFloat64(12, object.nativePromptMs);
        fbb.addFloat64(13, object.nativeDecodeMs);
        fbb.addFloat64(14, object.nativeTokenizeMs);
        fbb.addOffset(15, cacheModeOffset);
        fbb.addOffset(16, sessionTypeOffset);
        fbb.addInt64(17, object.promptTokens);
        fbb.addInt64(18, object.sampledTokens);
        fbb.addInt64(19, object.decodedTokens);
        fbb.addInt64(20, object.gpuLayers);
        fbb.addInt64(21, object.threads);
        fbb.addInt64(22, object.contextSize);
        fbb.addInt64(23, object.outputBytes);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final modelNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final backendParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final deviceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final generationSpeedTpsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final totalTokensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final tokenLatencyMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final openTimeMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final generateCallMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final nativeLoadMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final nativePromptMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final nativeDecodeMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final nativeTokenizeMsParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final cacheModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final sessionTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final promptTokensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final sampledTokensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final decodedTokensParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final gpuLayersParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final threadsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final contextSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final outputBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          50,
          0,
        );
        final object = MetricsEntry(
          id: idParam,
          timestamp: timestampParam,
          sessionId: sessionIdParam,
          modelName: modelNameParam,
          backend: backendParam,
          device: deviceParam,
          generationSpeedTps: generationSpeedTpsParam,
          totalTokens: totalTokensParam,
          tokenLatencyMs: tokenLatencyMsParam,
          openTimeMs: openTimeMsParam,
          generateCallMs: generateCallMsParam,
          nativeLoadMs: nativeLoadMsParam,
          nativePromptMs: nativePromptMsParam,
          nativeDecodeMs: nativeDecodeMsParam,
          nativeTokenizeMs: nativeTokenizeMsParam,
          cacheMode: cacheModeParam,
          sessionType: sessionTypeParam,
          promptTokens: promptTokensParam,
          sampledTokens: sampledTokensParam,
          decodedTokens: decodedTokensParam,
          gpuLayers: gpuLayersParam,
          threads: threadsParam,
          contextSize: contextSizeParam,
          outputBytes: outputBytesParam,
        );

        return object;
      },
    ),
    SessionEntity: obx_int.EntityDefinition<SessionEntity>(
      model: _entities[3],
      toOneRelations: (SessionEntity object) => [],
      toManyRelations: (SessionEntity object) => {},
      getId: (SessionEntity object) => object.id,
      setId: (SessionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SessionEntity object, fb.Builder fbb) {
        final sessionIdOffset = fbb.writeString(object.sessionId);
        final projectIdOffset = fbb.writeString(object.projectId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final forkOfOffset = object.forkOf == null
            ? null
            : fbb.writeString(object.forkOf!);
        final metadataJsonOffset = fbb.writeString(object.metadataJson);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sessionIdOffset);
        fbb.addOffset(2, projectIdOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addInt64(5, object.statusIndex);
        fbb.addInt64(6, object.modeIndex);
        fbb.addInt64(7, object.createdAt);
        fbb.addInt64(8, object.updatedAt);
        fbb.addInt64(9, object.lastActiveAt);
        fbb.addOffset(10, forkOfOffset);
        fbb.addBool(11, object.isPinned);
        fbb.addInt64(12, object.fileChanges);
        fbb.addInt64(13, object.messageCount);
        fbb.addInt64(14, object.pendingCount);
        fbb.addInt64(15, object.queueSize);
        fbb.addInt64(16, object.totalDurationMs);
        fbb.addBool(18, object.isSelected);
        fbb.addOffset(19, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sessionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final projectIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final modeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final updatedAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final lastActiveAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final forkOfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final isPinnedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final fileChangesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final messageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final pendingCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final queueSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final totalDurationMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final isSelectedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final object = SessionEntity(
          id: idParam,
          sessionId: sessionIdParam,
          projectId: projectIdParam,
          title: titleParam,
          description: descriptionParam,
          statusIndex: statusIndexParam,
          modeIndex: modeIndexParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          lastActiveAt: lastActiveAtParam,
          forkOf: forkOfParam,
          isPinned: isPinnedParam,
          fileChanges: fileChangesParam,
          messageCount: messageCountParam,
          pendingCount: pendingCountParam,
          queueSize: queueSizeParam,
          totalDurationMs: totalDurationMsParam,
          metadataJson: metadataJsonParam,
          isSelected: isSelectedParam,
        );

        return object;
      },
    ),
    AppSettingsEntity: obx_int.EntityDefinition<AppSettingsEntity>(
      model: _entities[4],
      toOneRelations: (AppSettingsEntity object) => [],
      toManyRelations: (AppSettingsEntity object) => {},
      getId: (AppSettingsEntity object) => object.id,
      setId: (AppSettingsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingsEntity object, fb.Builder fbb) {
        final themeModeOffset = fbb.writeString(object.themeMode);
        final conversationWidthOffset = fbb.writeString(
          object.conversationWidth,
        );
        final lightThemePresetOffset = fbb.writeString(object.lightThemePreset);
        final darkThemePresetOffset = fbb.writeString(object.darkThemePreset);
        final aiProviderOffset = fbb.writeString(object.aiProvider);
        final apiKeyOffset = fbb.writeString(object.apiKey);
        final wayangProBaseUrlOffset = fbb.writeString(object.wayangProBaseUrl);
        final wayangProGrpcUrlOffset = fbb.writeString(object.wayangProGrpcUrl);
        final openAiBaseUrlOffset = fbb.writeString(object.openAiBaseUrl);
        final anthropicBaseUrlOffset = fbb.writeString(object.anthropicBaseUrl);
        final geminiBaseUrlOffset = fbb.writeString(object.geminiBaseUrl);
        final defaultModelOffset = fbb.writeString(object.defaultModel);
        final systemPromptOffset = fbb.writeString(object.systemPrompt);
        final localLlmBackendOffset = fbb.writeString(object.localLlmBackend);
        final localModelPathOffset = fbb.writeString(object.localModelPath);
        final localModelNameOffset = fbb.writeString(object.localModelName);
        final ollamaBaseUrlOffset = fbb.writeString(object.ollamaBaseUrl);
        final securityPresetOffset = fbb.writeString(object.securityPreset);
        final outsideFolderFileAccessOffset = fbb.writeString(
          object.outsideFolderFileAccess,
        );
        final terminalExecutionPolicyOffset = fbb.writeString(
          object.terminalExecutionPolicy,
        );
        final artifactReviewPolicyOffset = fbb.writeString(
          object.artifactReviewPolicy,
        );
        final fileAccessRulesJsonOffset = fbb.writeString(
          object.fileAccessRulesJson,
        );
        final networkAccessRulesJsonOffset = fbb.writeString(
          object.networkAccessRulesJson,
        );
        final terminalCommandsJsonOffset = fbb.writeString(
          object.terminalCommandsJson,
        );
        final mcpToolsJsonOffset = fbb.writeString(object.mcpToolsJson);
        final jsExecutionPolicyOffset = fbb.writeString(
          object.jsExecutionPolicy,
        );
        final downloadPathOffset = fbb.writeString(object.downloadPath);
        final actuationRulesJsonOffset = fbb.writeString(
          object.actuationRulesJson,
        );
        final logLevelOffset = fbb.writeString(object.logLevel);
        final proxyUrlOffset = fbb.writeString(object.proxyUrl);
        final noProxyHostsOffset = fbb.writeString(object.noProxyHosts);
        fbb.startTable(58);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, themeModeOffset);
        fbb.addOffset(2, conversationWidthOffset);
        fbb.addOffset(3, lightThemePresetOffset);
        fbb.addOffset(4, darkThemePresetOffset);
        fbb.addBool(5, object.verboseAgentChat);
        fbb.addFloat64(6, object.fontSize);
        fbb.addOffset(7, aiProviderOffset);
        fbb.addOffset(8, apiKeyOffset);
        fbb.addOffset(9, wayangProBaseUrlOffset);
        fbb.addOffset(10, wayangProGrpcUrlOffset);
        fbb.addOffset(11, openAiBaseUrlOffset);
        fbb.addOffset(12, anthropicBaseUrlOffset);
        fbb.addOffset(13, geminiBaseUrlOffset);
        fbb.addOffset(14, defaultModelOffset);
        fbb.addOffset(15, systemPromptOffset);
        fbb.addBool(16, object.streamingEnabled);
        fbb.addInt64(17, object.maxTokens);
        fbb.addFloat64(18, object.temperature);
        fbb.addBool(19, object.autoSelectModel);
        fbb.addOffset(20, localLlmBackendOffset);
        fbb.addOffset(21, localModelPathOffset);
        fbb.addOffset(22, localModelNameOffset);
        fbb.addInt64(23, object.localContextSize);
        fbb.addInt64(24, object.localGpuLayers);
        fbb.addInt64(25, object.localThreads);
        fbb.addOffset(26, ollamaBaseUrlOffset);
        fbb.addBool(27, object.localEnableGpu);
        fbb.addOffset(28, securityPresetOffset);
        fbb.addOffset(29, outsideFolderFileAccessOffset);
        fbb.addOffset(30, terminalExecutionPolicyOffset);
        fbb.addBool(31, object.sandboxMode);
        fbb.addOffset(32, artifactReviewPolicyOffset);
        fbb.addOffset(33, fileAccessRulesJsonOffset);
        fbb.addOffset(34, networkAccessRulesJsonOffset);
        fbb.addOffset(35, terminalCommandsJsonOffset);
        fbb.addOffset(36, mcpToolsJsonOffset);
        fbb.addOffset(37, jsExecutionPolicyOffset);
        fbb.addInt64(38, object.browserViewportWidth);
        fbb.addInt64(39, object.browserViewportHeight);
        fbb.addOffset(40, downloadPathOffset);
        fbb.addBool(41, object.screenshotEnabled);
        fbb.addOffset(42, actuationRulesJsonOffset);
        fbb.addBool(43, object.desktopNotifications);
        fbb.addBool(44, object.soundEffects);
        fbb.addBool(45, object.taskCompletionAlert);
        fbb.addBool(46, object.errorAlert);
        fbb.addBool(47, object.telemetryEnabled);
        fbb.addBool(48, object.crashReporting);
        fbb.addBool(49, object.analyticsEnabled);
        fbb.addOffset(50, logLevelOffset);
        fbb.addBool(51, object.autoSave);
        fbb.addInt64(52, object.autoSaveIntervalSeconds);
        fbb.addBool(53, object.experimentalFeatures);
        fbb.addOffset(54, proxyUrlOffset);
        fbb.addOffset(55, noProxyHostsOffset);
        fbb.addBool(56, object.sslVerification);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AppSettingsEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..themeMode = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..conversationWidth = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..lightThemePreset = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..darkThemePreset = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..verboseAgentChat = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..fontSize = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..aiProvider = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..apiKey = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '')
          ..wayangProBaseUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '')
          ..wayangProGrpcUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..openAiBaseUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..anthropicBaseUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 28, '')
          ..geminiBaseUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 30, '')
          ..defaultModel = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 32, '')
          ..systemPrompt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 34, '')
          ..streamingEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            36,
            false,
          )
          ..maxTokens = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            38,
            0,
          )
          ..temperature = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            40,
            0,
          )
          ..autoSelectModel = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            42,
            false,
          )
          ..localLlmBackend = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 44, '')
          ..localModelPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 46, '')
          ..localModelName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 48, '')
          ..localContextSize = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            50,
            0,
          )
          ..localGpuLayers = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            52,
            0,
          )
          ..localThreads = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            54,
            0,
          )
          ..ollamaBaseUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 56, '')
          ..localEnableGpu = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            58,
            false,
          )
          ..securityPreset = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 60, '')
          ..outsideFolderFileAccess = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 62, '')
          ..terminalExecutionPolicy = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 64, '')
          ..sandboxMode = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            66,
            false,
          )
          ..artifactReviewPolicy = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 68, '')
          ..fileAccessRulesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 70, '')
          ..networkAccessRulesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 72, '')
          ..terminalCommandsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 74, '')
          ..mcpToolsJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 76, '')
          ..jsExecutionPolicy = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 78, '')
          ..browserViewportWidth = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            80,
            0,
          )
          ..browserViewportHeight = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            82,
            0,
          )
          ..downloadPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 84, '')
          ..screenshotEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            86,
            false,
          )
          ..actuationRulesJson = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 88, '')
          ..desktopNotifications = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            90,
            false,
          )
          ..soundEffects = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            92,
            false,
          )
          ..taskCompletionAlert = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            94,
            false,
          )
          ..errorAlert = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            96,
            false,
          )
          ..telemetryEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            98,
            false,
          )
          ..crashReporting = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            100,
            false,
          )
          ..analyticsEnabled = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            102,
            false,
          )
          ..logLevel = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 104, '')
          ..autoSave = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            106,
            false,
          )
          ..autoSaveIntervalSeconds = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            108,
            0,
          )
          ..experimentalFeatures = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            110,
            false,
          )
          ..proxyUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 112, '')
          ..noProxyHosts = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 114, '')
          ..sslVerification = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            116,
            false,
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AttachmentEntity] entity fields to define ObjectBox queries.
class AttachmentEntity_ {
  /// See [AttachmentEntity.id].
  static final id = obx.QueryIntegerProperty<AttachmentEntity>(
    _entities[0].properties[0],
  );

  /// See [AttachmentEntity.attachmentId].
  static final attachmentId = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[1],
  );

  /// See [AttachmentEntity.name].
  static final name = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[2],
  );

  /// See [AttachmentEntity.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<AttachmentEntity>(
    _entities[0].properties[3],
  );

  /// See [AttachmentEntity.url].
  static final url = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[4],
  );

  /// See [AttachmentEntity.localPath].
  static final localPath = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[5],
  );

  /// See [AttachmentEntity.size].
  static final size = obx.QueryIntegerProperty<AttachmentEntity>(
    _entities[0].properties[6],
  );

  /// See [AttachmentEntity.mimeType].
  static final mimeType = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[7],
  );

  /// See [AttachmentEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<AttachmentEntity>(
    _entities[0].properties[8],
  );

  /// See [AttachmentEntity.thumbnailUrl].
  static final thumbnailUrl = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[9],
  );

  /// See [AttachmentEntity.durationMs].
  static final durationMs = obx.QueryIntegerProperty<AttachmentEntity>(
    _entities[0].properties[10],
  );

  /// See [AttachmentEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[11],
  );

  /// See [AttachmentEntity.chatEntryId].
  static final chatEntryId = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[12],
  );

  /// See [AttachmentEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<AttachmentEntity>(
    _entities[0].properties[13],
  );
}

/// [ChatEntryEntity] entity fields to define ObjectBox queries.
class ChatEntryEntity_ {
  /// See [ChatEntryEntity.id].
  static final id = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[0],
  );

  /// See [ChatEntryEntity.entryId].
  static final entryId = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[1],
  );

  /// See [ChatEntryEntity.sessionId].
  static final sessionId = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[2],
  );

  /// See [ChatEntryEntity.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[3],
  );

  /// See [ChatEntryEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[4],
  );

  /// See [ChatEntryEntity.text].
  static final text = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[5],
  );

  /// See [ChatEntryEntity.isLoading].
  static final isLoading = obx.QueryBooleanProperty<ChatEntryEntity>(
    _entities[1].properties[6],
  );

  /// See [ChatEntryEntity.timestamp].
  static final timestamp = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[7],
  );

  /// See [ChatEntryEntity.toolCallId].
  static final toolCallId = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[8],
  );

  /// See [ChatEntryEntity.toolCallKindIndex].
  static final toolCallKindIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[9],
  );

  /// See [ChatEntryEntity.toolCallSummary].
  static final toolCallSummary = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[10],
  );

  /// See [ChatEntryEntity.toolCallDetailInput].
  static final toolCallDetailInput = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[11],
  );

  /// See [ChatEntryEntity.toolCallDetailOutput].
  static final toolCallDetailOutput = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[12],
  );

  /// See [ChatEntryEntity.toolCallStatusIndex].
  static final toolCallStatusIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[13],
  );

  /// See [ChatEntryEntity.toolCallRiskIndex].
  static final toolCallRiskIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[14],
  );

  /// See [ChatEntryEntity.toolCallDurationMs].
  static final toolCallDurationMs = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[15],
  );

  /// See [ChatEntryEntity.toolCallErrorMessage].
  static final toolCallErrorMessage = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[16],
  );

  /// See [ChatEntryEntity.toolCallSubtasks].
  static final toolCallSubtasks = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[17],
  );

  /// See [ChatEntryEntity.toolCallResult].
  static final toolCallResult = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[18],
  );

  /// See [ChatEntryEntity.toolCallProgress].
  static final toolCallProgress = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[19],
  );

  /// See [ChatEntryEntity.toolCallIsBlocking].
  static final toolCallIsBlocking = obx.QueryBooleanProperty<ChatEntryEntity>(
    _entities[1].properties[20],
  );

  /// See [ChatEntryEntity.approvalId].
  static final approvalId = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[21],
  );

  /// See [ChatEntryEntity.approvalCommand].
  static final approvalCommand = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[22],
  );

  /// See [ChatEntryEntity.approvalReason].
  static final approvalReason = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[23],
  );

  /// See [ChatEntryEntity.approvalRiskIndex].
  static final approvalRiskIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[24],
  );

  /// See [ChatEntryEntity.approvalStatusIndex].
  static final approvalStatusIndex = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[25],
  );

  /// See [ChatEntryEntity.planTitle].
  static final planTitle = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[26],
  );

  /// See [ChatEntryEntity.planSteps].
  static final planSteps = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[27],
  );

  /// See [ChatEntryEntity.errorMessage].
  static final errorMessage = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[28],
  );

  /// See [ChatEntryEntity.retryCount].
  static final retryCount = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[29],
  );

  /// See [ChatEntryEntity.jobId].
  static final jobId = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[30],
  );

  /// See [ChatEntryEntity.queuePosition].
  static final queuePosition = obx.QueryIntegerProperty<ChatEntryEntity>(
    _entities[1].properties[31],
  );

  /// See [ChatEntryEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<ChatEntryEntity>(
    _entities[1].properties[32],
  );
}

/// [MetricsEntry] entity fields to define ObjectBox queries.
class MetricsEntry_ {
  /// See [MetricsEntry.id].
  static final id = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[0],
  );

  /// See [MetricsEntry.timestamp].
  static final timestamp = obx.QueryDateProperty<MetricsEntry>(
    _entities[2].properties[1],
  );

  /// See [MetricsEntry.sessionId].
  static final sessionId = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[2],
  );

  /// See [MetricsEntry.modelName].
  static final modelName = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[3],
  );

  /// See [MetricsEntry.backend].
  static final backend = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[4],
  );

  /// See [MetricsEntry.device].
  static final device = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[5],
  );

  /// See [MetricsEntry.generationSpeedTps].
  static final generationSpeedTps = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[6],
  );

  /// See [MetricsEntry.totalTokens].
  static final totalTokens = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[7],
  );

  /// See [MetricsEntry.tokenLatencyMs].
  static final tokenLatencyMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[8],
  );

  /// See [MetricsEntry.openTimeMs].
  static final openTimeMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[9],
  );

  /// See [MetricsEntry.generateCallMs].
  static final generateCallMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[10],
  );

  /// See [MetricsEntry.nativeLoadMs].
  static final nativeLoadMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[11],
  );

  /// See [MetricsEntry.nativePromptMs].
  static final nativePromptMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[12],
  );

  /// See [MetricsEntry.nativeDecodeMs].
  static final nativeDecodeMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[13],
  );

  /// See [MetricsEntry.nativeTokenizeMs].
  static final nativeTokenizeMs = obx.QueryDoubleProperty<MetricsEntry>(
    _entities[2].properties[14],
  );

  /// See [MetricsEntry.cacheMode].
  static final cacheMode = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[15],
  );

  /// See [MetricsEntry.sessionType].
  static final sessionType = obx.QueryStringProperty<MetricsEntry>(
    _entities[2].properties[16],
  );

  /// See [MetricsEntry.promptTokens].
  static final promptTokens = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[17],
  );

  /// See [MetricsEntry.sampledTokens].
  static final sampledTokens = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[18],
  );

  /// See [MetricsEntry.decodedTokens].
  static final decodedTokens = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[19],
  );

  /// See [MetricsEntry.gpuLayers].
  static final gpuLayers = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[20],
  );

  /// See [MetricsEntry.threads].
  static final threads = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[21],
  );

  /// See [MetricsEntry.contextSize].
  static final contextSize = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[22],
  );

  /// See [MetricsEntry.outputBytes].
  static final outputBytes = obx.QueryIntegerProperty<MetricsEntry>(
    _entities[2].properties[23],
  );
}

/// [SessionEntity] entity fields to define ObjectBox queries.
class SessionEntity_ {
  /// See [SessionEntity.id].
  static final id = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[0],
  );

  /// See [SessionEntity.sessionId].
  static final sessionId = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[1],
  );

  /// See [SessionEntity.projectId].
  static final projectId = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[2],
  );

  /// See [SessionEntity.title].
  static final title = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[3],
  );

  /// See [SessionEntity.description].
  static final description = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[4],
  );

  /// See [SessionEntity.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[5],
  );

  /// See [SessionEntity.modeIndex].
  static final modeIndex = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[6],
  );

  /// See [SessionEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[7],
  );

  /// See [SessionEntity.updatedAt].
  static final updatedAt = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[8],
  );

  /// See [SessionEntity.lastActiveAt].
  static final lastActiveAt = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[9],
  );

  /// See [SessionEntity.forkOf].
  static final forkOf = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[10],
  );

  /// See [SessionEntity.isPinned].
  static final isPinned = obx.QueryBooleanProperty<SessionEntity>(
    _entities[3].properties[11],
  );

  /// See [SessionEntity.fileChanges].
  static final fileChanges = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[12],
  );

  /// See [SessionEntity.messageCount].
  static final messageCount = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[13],
  );

  /// See [SessionEntity.pendingCount].
  static final pendingCount = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[14],
  );

  /// See [SessionEntity.queueSize].
  static final queueSize = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[15],
  );

  /// See [SessionEntity.totalDurationMs].
  static final totalDurationMs = obx.QueryIntegerProperty<SessionEntity>(
    _entities[3].properties[16],
  );

  /// See [SessionEntity.isSelected].
  static final isSelected = obx.QueryBooleanProperty<SessionEntity>(
    _entities[3].properties[17],
  );

  /// See [SessionEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<SessionEntity>(
    _entities[3].properties[18],
  );
}

/// [AppSettingsEntity] entity fields to define ObjectBox queries.
class AppSettingsEntity_ {
  /// See [AppSettingsEntity.id].
  static final id = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[4].properties[0],
  );

  /// See [AppSettingsEntity.themeMode].
  static final themeMode = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[1],
  );

  /// See [AppSettingsEntity.conversationWidth].
  static final conversationWidth = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[2],
  );

  /// See [AppSettingsEntity.lightThemePreset].
  static final lightThemePreset = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[3],
  );

  /// See [AppSettingsEntity.darkThemePreset].
  static final darkThemePreset = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[4],
  );

  /// See [AppSettingsEntity.verboseAgentChat].
  static final verboseAgentChat = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[5],
  );

  /// See [AppSettingsEntity.fontSize].
  static final fontSize = obx.QueryDoubleProperty<AppSettingsEntity>(
    _entities[4].properties[6],
  );

  /// See [AppSettingsEntity.aiProvider].
  static final aiProvider = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[7],
  );

  /// See [AppSettingsEntity.apiKey].
  static final apiKey = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[8],
  );

  /// See [AppSettingsEntity.wayangProBaseUrl].
  static final wayangProBaseUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[9],
  );

  /// See [AppSettingsEntity.wayangProGrpcUrl].
  static final wayangProGrpcUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[10],
  );

  /// See [AppSettingsEntity.openAiBaseUrl].
  static final openAiBaseUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[11],
  );

  /// See [AppSettingsEntity.anthropicBaseUrl].
  static final anthropicBaseUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[12],
  );

  /// See [AppSettingsEntity.geminiBaseUrl].
  static final geminiBaseUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[13],
  );

  /// See [AppSettingsEntity.defaultModel].
  static final defaultModel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[14],
  );

  /// See [AppSettingsEntity.systemPrompt].
  static final systemPrompt = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[15],
  );

  /// See [AppSettingsEntity.streamingEnabled].
  static final streamingEnabled = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[16],
  );

  /// See [AppSettingsEntity.maxTokens].
  static final maxTokens = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[4].properties[17],
  );

  /// See [AppSettingsEntity.temperature].
  static final temperature = obx.QueryDoubleProperty<AppSettingsEntity>(
    _entities[4].properties[18],
  );

  /// See [AppSettingsEntity.autoSelectModel].
  static final autoSelectModel = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[19],
  );

  /// See [AppSettingsEntity.localLlmBackend].
  static final localLlmBackend = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[20],
  );

  /// See [AppSettingsEntity.localModelPath].
  static final localModelPath = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[21],
  );

  /// See [AppSettingsEntity.localModelName].
  static final localModelName = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[22],
  );

  /// See [AppSettingsEntity.localContextSize].
  static final localContextSize = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[4].properties[23],
  );

  /// See [AppSettingsEntity.localGpuLayers].
  static final localGpuLayers = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[4].properties[24],
  );

  /// See [AppSettingsEntity.localThreads].
  static final localThreads = obx.QueryIntegerProperty<AppSettingsEntity>(
    _entities[4].properties[25],
  );

  /// See [AppSettingsEntity.ollamaBaseUrl].
  static final ollamaBaseUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[26],
  );

  /// See [AppSettingsEntity.localEnableGpu].
  static final localEnableGpu = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[27],
  );

  /// See [AppSettingsEntity.securityPreset].
  static final securityPreset = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[28],
  );

  /// See [AppSettingsEntity.outsideFolderFileAccess].
  static final outsideFolderFileAccess =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[4].properties[29]);

  /// See [AppSettingsEntity.terminalExecutionPolicy].
  static final terminalExecutionPolicy =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[4].properties[30]);

  /// See [AppSettingsEntity.sandboxMode].
  static final sandboxMode = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[31],
  );

  /// See [AppSettingsEntity.artifactReviewPolicy].
  static final artifactReviewPolicy =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[4].properties[32]);

  /// See [AppSettingsEntity.fileAccessRulesJson].
  static final fileAccessRulesJson = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[33],
  );

  /// See [AppSettingsEntity.networkAccessRulesJson].
  static final networkAccessRulesJson =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[4].properties[34]);

  /// See [AppSettingsEntity.terminalCommandsJson].
  static final terminalCommandsJson =
      obx.QueryStringProperty<AppSettingsEntity>(_entities[4].properties[35]);

  /// See [AppSettingsEntity.mcpToolsJson].
  static final mcpToolsJson = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[36],
  );

  /// See [AppSettingsEntity.jsExecutionPolicy].
  static final jsExecutionPolicy = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[37],
  );

  /// See [AppSettingsEntity.browserViewportWidth].
  static final browserViewportWidth =
      obx.QueryIntegerProperty<AppSettingsEntity>(_entities[4].properties[38]);

  /// See [AppSettingsEntity.browserViewportHeight].
  static final browserViewportHeight =
      obx.QueryIntegerProperty<AppSettingsEntity>(_entities[4].properties[39]);

  /// See [AppSettingsEntity.downloadPath].
  static final downloadPath = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[40],
  );

  /// See [AppSettingsEntity.screenshotEnabled].
  static final screenshotEnabled = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[41],
  );

  /// See [AppSettingsEntity.actuationRulesJson].
  static final actuationRulesJson = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[42],
  );

  /// See [AppSettingsEntity.desktopNotifications].
  static final desktopNotifications =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[4].properties[43]);

  /// See [AppSettingsEntity.soundEffects].
  static final soundEffects = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[44],
  );

  /// See [AppSettingsEntity.taskCompletionAlert].
  static final taskCompletionAlert =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[4].properties[45]);

  /// See [AppSettingsEntity.errorAlert].
  static final errorAlert = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[46],
  );

  /// See [AppSettingsEntity.telemetryEnabled].
  static final telemetryEnabled = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[47],
  );

  /// See [AppSettingsEntity.crashReporting].
  static final crashReporting = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[48],
  );

  /// See [AppSettingsEntity.analyticsEnabled].
  static final analyticsEnabled = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[49],
  );

  /// See [AppSettingsEntity.logLevel].
  static final logLevel = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[50],
  );

  /// See [AppSettingsEntity.autoSave].
  static final autoSave = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[51],
  );

  /// See [AppSettingsEntity.autoSaveIntervalSeconds].
  static final autoSaveIntervalSeconds =
      obx.QueryIntegerProperty<AppSettingsEntity>(_entities[4].properties[52]);

  /// See [AppSettingsEntity.experimentalFeatures].
  static final experimentalFeatures =
      obx.QueryBooleanProperty<AppSettingsEntity>(_entities[4].properties[53]);

  /// See [AppSettingsEntity.proxyUrl].
  static final proxyUrl = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[54],
  );

  /// See [AppSettingsEntity.noProxyHosts].
  static final noProxyHosts = obx.QueryStringProperty<AppSettingsEntity>(
    _entities[4].properties[55],
  );

  /// See [AppSettingsEntity.sslVerification].
  static final sslVerification = obx.QueryBooleanProperty<AppSettingsEntity>(
    _entities[4].properties[56],
  );
}
